name: Paper Trading Bot - Every 15 Minutes (Market Hours IST)

on:
  schedule:
    # Runs every 15 minutes between 4:00 and 9:30 UTC (which is 9:30–15:00 IST)
    - cron: "*/15 4-9 * * 1-5"

  workflow_dispatch:  # Manual run

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install yfinance pandas numpy

      - name: Run Paper Trading Bot
        run: |
          python paper_trader.py

      - name: Configure Git
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "actions@github.com"

      - name: Commit CSV changes
        run: |
          git add *.csv || true
          git commit -m "Auto-update: Paper trading CSV logs" || echo "No changes to commit"
          git push
